export const productsData = [
  {
    id: 1,
    sku: 185523665458666,
    title: "spkhl Tie Dye Gray T-Shirt",
    quantity: 1,
    description: "sph Tie Dye Gray",
    availableSizes: ["X", "L", "XL", "XXL"],
    price: 10,
    isFreeShipping: true,
  },
  {
    id: 2,
    sku: 18555522458666,
    title: "Danger Knife Gray T-Shirt",
    quantity: 1,
    description: "Danger Knife Gray",
    availableSizes: ["X", "L", "M"],
    price: 14.9,
    isFreeShipping: true,
  },
  {
    id: 3,
    sku: 1869833665458666,
    title: "White DGK Script Tee",
    quantity: 1,
    description: "White DGK Script Tee",
    availableSizes: ["X", "L", "M"],
    price: 14.9,
    isFreeShipping: true,
  },
  {
    id: 4,
    sku: 999523668555666,
    title: "Born on the Streets T-Shirt",
    quantity: 1,
    description: "Born on the Streets",
    availableSizes: ["XL"],
    price: 25.9,
    isFreeShipping: false,
  },
  {
    id: 5,
    sku: 188552223335566,
    title: "Tso 3D Short Sleeve",
    quantity: 1,
    description: "sph Tie Dye Gray",
    availableSizes: ["X", "L", "XL"],
    price: 10.9,
    isFreeShipping: false,
  },
  {
    id: 6,
    sku: 455221584225233,
    title: "Man Tie Dye Cinza Gray T-Shirt",
    quantity: 1,
    description: "Man Tie Dye Cinza Gray",
    availableSizes: ["XL", "XXL"],
    price: 49.9,
    isFreeShipping: false,
  },
  {
    id: 7,
    sku: 555421148753663,
    title: "Crazy Monkey Black T-Shirt",
    quantity: 1,
    description: "1977 Infantil",
    availableSizes: ["S"],
    style: "Preto com listras brances",
    price: 22.5,
    isFreeShipping: true,
  },
  {
    id: 8,
    sku: 5687441148753663,
    title: "Tso 3D Black T-Shirt",
    quantity: 1,
    description: "",
    availableSizes: ["XL"],
    style: "Azul escure",
    price: 18.7,
    isFreeShipping: false,
  },
  {
    id: 9,
    sku: 555421148753663,
    title: "Crazy Monkey Gray",
    quantity: 1,
    description: "",
    availableSizes: ["L", "XL"],
    price: 134.9,
    isFreeShipping: true,
  },
];
